language: node_js
node_js:
    - "6"
    - "8"
before_install: if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
after_script: npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
